#!/bin/bash
#run_symptoms.sh
#Run learn.py for all symptom files generated by parse_xlsx_data.py
#Run 4 files at a time

#Oliver Evans
#4-5-16

cd /home/oevans/chiari/data/symptoms

max_jobs=3

args=()
i=0
n=0
for file in *
do
    args[n]="symptoms/${file%.*}"
    ((n++))
done

echo "n=$n"

for a in "${args[@]}"
do
    echo "$i: $a"
    ((i++))
done

# > "/home/oevans/chiari/logs/nohup/${args[i]}" &

i=0
while [ $i -lt $n ]
do
    echo
    echo "i=$i"
    #Check how many python jobs are running now
    running=$(ps -A | grep -c python)
    echo "running=$running"
    if [ $running -lt $max_jobs ]
    then
        echo "Run ${args[i]}"
        nohup python "/home/oevans/chiari/python/learn.py" "${args[i]}" &
        ((i++))
        sleep 3
    else
        sleep 60
    fi
done
