#!/bin/bash
#run_symptoms.sh
#Run learn.py for all symptom files generated by parse_xlsx_data.py
#Run 1 file at a time

#Run this file using:
#nohup ./run_serial.sh > ../logs/nohup/run_serial.txt &

#python has -u flag to write to log immediately rather than waiting until the end

cd /home/oevans/chiari/data/symptoms

symptom_files=($(echo data/symptoms/* | sed 's#data/symptoms/##g'))
echo "Symptom files: ${symptom_files[@]}"

for file in ${symptom_files[@]}
do
    echo "Running $file"
    date "+%H:%M%p %m-%d-%Y"
    sh -c "python -u /home/oevans/chiari/python/learn.py symptoms/${file%.*}" #> "/home/oevans/chiari/logs/nohup/symptoms/$file"
    echo
done

echo "Done!"
date "+%H:%M%p %m-%d-%Y"

